apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: springapp
          image: rohan91196/trial-web:v1
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql          
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_PORT
              value: "3306"

