apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30001   # This is an example port number; choose an available port in your cluster
  type: NodePort